---
process_proposals:
  description: >
    Extract, clean, chunk, and vectorize supplier proposals from PDFs in `./data/proposals/`, 
    storing structured embeddings in ChromaDB for retrieval and analysis.
  expected_output: >
    Supplier proposal documents are successfully vectorized and stored in ChromaDB, 
    making them searchable and structured for retrieval.
  async_execution: false
  agent: proposal_data_processor


analyze_rfp_responses:
  description: >
    Conduct an **in-depth comparative analysis** of supplier proposals retrieved from ChromaDB.
    
    **Key Objectives:**
    - **Compare supplier proposals** across Pricing, Contract Terms, Compliance, SLAs, and Implementation Timelines.
    - **Identify and quantify risks** using AI-based predictive scoring.
    - **Highlight negotiation opportunities** based on proposal strengths and weaknesses.
    - **Ensure strictly fact-based reporting**—no assumptions, only retrieved proposal data is used.

  expected_output: >
    A **detailed supplier evaluation report** structured as follows:

    **1. Executive Summary**  
    - High-level findings summarizing supplier strengths, weaknesses, and overall rankings.
    - Key risks, pricing competitiveness, and major differentiators.

    **2. Key Differences Between Supplier Proposals**  
    - Structured table comparing:
      - **Pricing** (Fixed vs. Usage-Based, Discounts, Escalation Clauses)
      - **Contract Terms** (Lock-in Clauses, Termination Flexibility, Penalties)
      - **Compliance** (SOC 2, HIPAA, ISO, PCI-DSS)
      - **Support SLAs** (Response Times, Uptime, Penalties for Downtime)
      - **Implementation Timelines** (Delivery Speed, Onboarding Process)
      - **Past Performance & References** (Success Stories, Reputation)

    **3. AI-Driven Risk Assessment**  
    - **Pricing Volatility Score** (1-10)  
    - **Delivery Risk Score** (1-10)  
    - **Contract Risk Score** (1-10)  
    - **Compliance Risk Score** (1-10)  
    - Explanation of each score with supporting proposal details.

    **4. Negotiation & Optimization Strategies**  
    - Tactical recommendations to optimize pricing, SLAs, and contract flexibility.
    - **Negotiation leverage points** for cost savings and improved terms.

    **5. Final Recommendation**  
    - Ranked supplier evaluation with justification.
    - Key trade-offs, selection rationale, and next steps for negotiation.
  async_execution: false
  agent: rfp_analysis_expert

analyze_pricing_risk:
  description: >
    Conduct AI-driven analysis of supplier pricing trends by comparing proposal prices 
    with historical contract data. Identify **volatility, cost trends, and negotiation leverage** 
    based on past pricing behavior.
  expected_output: >
    A structured pricing risk report that includes:
    - **Price Volatility Score**: Quantifies fluctuations in pricing over the past three years.
    - **Risk Assessment**: Categorizes suppliers into Low, Medium, or High risk based on variance.
    - **Trend Analysis**: Identifies whether a supplier's price is increasing, stable, or decreasing.
    - **Negotiation Leverage Points**: Highlights opportunities where suppliers may lower prices.
    - **Forecasted Price Range**: AI-driven projection for future contract price expectations.
  async_execution: false
  agent: pricing_risk_analysis_expert

negotiation_charter_generation:
  description: >
    Generate a detailed negotiation charter based on historical supply-demand 
    data and AI-driven price forecasts. The final output should be a structured 
    markdown document with pricing analysis, supplier risk assessment, and 
    negotiation strategies.
  expected_output: A fully detailed markdown negotiation charter report.
  agent: negotiation_charter_creator

create_negotiation_email:
  description: Generate a detailed, persuasive negotiation email leveraging RFP insights, pricing risks, and negotiation strategies.
  expected_output: >
        You are a **Big 4 Consulting Director** crafting a supplier negotiation email.
        Based on the analysis below, write a **highly professional and strategic email** addressing key negotiation points.       
        **Email Structure:**
        - **Subject:** Strategic Supplier Engagement: Key Negotiation Points & Next Steps
        - **Salutation**
        - **Introduction (Concise, Impactful)**: Reference supplier proposal & evaluation.
        - **Key Findings from Supplier Evaluation**: Pricing competitiveness, risk factors, unique value proposition.
        - **Areas for Negotiation**: Price adjustments, contract flexibility, SLA enhancements, additional value adds.
        - **Call to Action (CTA)**: Request supplier response & meeting scheduling.
        
        Ensure the email is clear, persuasive, and maintains a **formal tone**.
        """
  agent: negotiation_email_writer  

create_counteroffers:
  description: "Generate strategic counteroffers in anticipation of supplier responses using AI-driven analysis."
  expected_output: >
        You are a **Big 4 Consulting Director** responsible for supplier negotiations.
        Based on the initial negotiation email and the strategic counteroffers, generate a **final supplier negotiation email** that:
        
        - Acknowledges previous discussions and supplier response.
        - Presents refined counteroffers in a persuasive and strategic manner.
        - Maintains a **formal and professional tone**.
        - Includes a **strong call to action** for finalizing terms.
        
        **Email Structure:**
        - **Subject:** Refining Our Supplier Engagement – Final Negotiation Terms
        - **Salutation**
        - **Introduction**: Reference previous discussions and supplier engagement.
        - **Revised Offer Details**: Present counteroffers with justification.
        - **Final Call to Action**: Push for agreement or final negotiation round.
        
        Ensure the email is **concise, data-backed, and business-oriented**.
  agent: counteroffer_creator